# Generated by Django 3.0.8 on 2020-07-13 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='users_profils/')),
                ('bio', models.TextField(null=True)),
                ('licensenumber', models.CharField(max_length=300, null=True)),
                ('dateofbirth', models.DateField(null=True)),
                ('placeofbirth', models.CharField(max_length=300, null=True)),
                ('address', models.CharField(max_length=300, null=True)),
                ('profile', models.CharField(choices=[('LM Engineer', 'lm engineer'), ('Quality Manager', 'quality manager')], max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
