# Generated by Django 3.0.8 on 2020-07-13 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleactivity', models.CharField(choices=[('Training', 'training'), ('Perform', 'perform'), ('Supervise', 'supervise'), ('CRS', 'crs')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TypeTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singletask', models.CharField(choices=[('EOT', 'eot'), ('SGH', 'sgh'), ('R/I', 'r/i'), ('MFI', 'mfi'), ('TS', 'ts'), ('MOD', 'mod'), ('REP', 'rep'), ('INSP', 'isnp'), ('FOT', 'fot'), ('MEL', 'mel')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='posts/')),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='maintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=300)),
                ('actype', models.CharField(max_length=300)),
                ('acregistration', models.CharField(max_length=250)),
                ('typemaintenance', models.CharField(max_length=300)),
                ('privilege', models.CharField(choices=[('B1', 'b1'), ('B2', 'b2')], max_length=2, null=True)),
                ('ata', models.IntegerField()),
                ('operation', models.CharField(max_length=300)),
                ('time', models.IntegerField()),
                ('maintenanceref', models.CharField(max_length=300)),
                ('remark', models.TextField(null=True)),
                ('activitytype', models.ManyToManyField(blank=True, related_name='typeact', to='maintenance.TypeActivities')),
                ('tasktype', models.ManyToManyField(blank=True, related_name='typetask', to='maintenance.TypeTasks')),
                ('technicalrecorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
